theme: jekyll-theme-minimal
title: 'Microbial Community Analysis (amplicons)'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Welcome
    url: base/welcome
  - title: Schedule
    url: base/schedule
#  - title: What is Bioinformatics/Genomics?
#    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_Oct_2020.pdf

  - heading: Support
#  - title: Zoom
#    url: base/zoom
#  - title: Slack
#    url: base/slack
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: Introduction to Command Line Part 1
    url: cli/command-line-intro1
  - title: Introduction to Command Line Part 2
    url: cli/command-line-intro2
  - title: Introduction to Command Line Part 3
    url: cli/command-line-intro3
#  - title: Day 3 Homework Solution
#    url: cli/day3_homework_solution

#  - heading: Data Reduction

#  - heading: Data Analysis

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-Alliance-Makerere_Covid
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
